### ISSUE TITLE
Question: Why []Payload ?

### ISSUE THREAD

**Issue by KtorZ** [brocaar/lorawan#1]
Hey !
Awesome job with the package. 
Still, one thing raises a question, in the implementation of the `MACPayload` the `FRMPayload` has a `[]Payload` type. Looking at LoRaWAN I don't see a clue about several payloads that could be sent within one MACPayload. I may be wrong but then I would appreciate to be enlightened on that point :) 
So far, as I understand, the frame payload `FRMPayload` either comes from the application embedded on the end-device if it's data related or from a layer above if it's mac-related. In both cases nevertheless it is unique, isn't it ?

Thanks

**Comment by brocaar** [comment]
As far as I understood from the specs it is possible to send multiple mac commands as one payload (as long as you don't exeed the max ``FRMPayload`` length):

```
A single data frame can contain any sequence of MAC commands, either piggybacked in the
FOpts field or, when sent as a separate data frame, in the FRMPayload field with the FPort
field being set to 0. Piggybacked MAC commands are always sent without encryption and
must not exceed 15 octets. MAC commands sent as FRMPayload are always encrypted
and must not exceed the maximum FRMPayload length.
```

When the ``lorawan`` package sees it contains mac commands (``FPort = 0``) it will combine these mac commands (and their payloads) as one ``DataPayload`` when encrypting, and it will break up the single ``DataPayload`` into separate payloads when decrypting.

So each ``FRMPayload`` will then be of type ``MACCommand``, and based on it's ``CID``, you're able to cast it's ``Payload`` (if it has one) into the right type (e.g. a ``LinkCheckAnsPayload`` type).

**Comment by KtorZ** [comment]
Ho. This is completely right, I forgot about that point on MAC commands. Thanks for reminding me!
