### ISSUE TITLE
Handle unknown MAC commands according to LoRaWAN specification

### ISSUE THREAD

**Issue by htdvisser** [brocaar/lorawan#17]
Returning an error in https://github.com/brocaar/lorawan/blob/master/fhdr.go#L198 stops processing of the entire message, while the LoRaWAN specification only says that "the first unknown MAC command terminates the processing of the MAC command sequence" (v1.0.1, bottom of page 22).

A simple `break` would resolve this issue, but in some cases it might be good to log an error as well. (See https://github.com/TheThingsNetwork/lora-gateway-bridge/commit/d5662313741364a129709b9b522ef29eacce0438)

**Comment by brocaar** [comment]
Cheers. Will look into it later this week!

**Comment by brocaar** [comment]
Hi @htdvisser this has been fixed in 5dcb3accd0694379a4db94be75fa721867c59739.
