### ISSUE TITLE
DecryptJoinAcceptPayload function appears to be encrypting not decrypting

### ISSUE THREAD

**Issue by jspangar** [brocaar/lorawan#23]
Code here appears to invoke an encypt function when it is supposed to be decrypting. Is this a bug? Ditto for the encrypt function (which is decrypting).

https://github.com/brocaar/lorawan/blob/master/phypayload.go#L363

**Comment by brocaar** [comment]
Good spot, however this is correct behaviour :-)

LoRaWAN specs:
> 10 The join-accept message itself is encrypted with the AppKey as follows:
> 11 aes128_decrypt(AppKey, AppNonce | NetID | DevAddr | DLSettings | RxDelay | CFList |
> 12 MIC)

> Note: The network server uses an AES decrypt operation in ECB mode to encrypt the join-accept message so that the end-device can use an AES encrypt operation to decrypt the message. __This way an end-device only has to implement AES encrypt but not AES decrypt.__
