### ISSUE TITLE
Main package, and pointing IP  lorawan

### ISSUE THREAD

**Issue by RogerioCassares** [brocaar/lorawan#26]
Hi Brocaar! 
It's me, again :)

Just summing up:
-> lora server-setup is ok, up and running
-> lora gateway bridge is correctly giving the outputs
-> lora server and lora server-app is running ok !
-> I know the node is activated, transmiting and receiving by the LoRa server analysing the "sents frames" on Gateway guide. (we've signal with a LED flash when node receive confirmed data).

So, lastly I could run the lorawan in Go packets! 

I've installed Go and go tools correctly and also I've run the "golang -getting started" an some "golang examples" from repository on github. 

I've prepared, install and build your packages from this repository, by using "go get github.com/brocaar/lorawan" so the packets are correctly installed on repository on my computer. 

Questions: 

1. It's possible run this program in the same local network? The server is in a PC "10.193.101.11" and i'am tryng to run the go package in "10.193.101.12". they are connected by a just by-pass router. 

2. In case of running ok from different PCs how can I point? there is in the codes?

3. There is a ready example implementation that I can run and see the data from the node, please? Or I have to make the 'main" package with the import "github.com/brocaar/lorawan" command line and respectives functions in func main () ?

I will looking forward your answer!
Best Regards,

Rogerio

**Comment by brocaar** [comment]
Hi @RogerioCassares, please not that this repository does not contain a program. This repository contains a library to read LoRaWAN frames. Unless you want to go low-level, there is no need to use this (although LoRa Server and LoRa App Server are both using this library). 

Here are a couple examples of how this library can be used:
https://godoc.org/github.com/brocaar/lorawan#example-PHYPayload--Decode

**Comment by RogerioCassares** [comment]
Hi Brocaar, i've wrote according you said me in my main package in "github.com/user/example-decode directory with example-decode.go file. 

I've copied the example inside func main (){ }

![captura de tela de 2017-05-26 16-45-42](https://cloud.githubusercontent.com/assets/25107890/26510247/d2b773c2-4232-11e7-8848-53e75ad81f9a.png)

and the out put was:

roger@LoRa-PC:~/go/src/github.com/user/lora-app/example-decode$ go run example-decode.go
# command-line-arguments
_./example-decode.go:3: imported and not used: "github.com/brocaar/lorawan"_
_./example-decode.go:12: undefined: PHYPayload_
roger@LoRa-PC:~/go/src/github.com/user/lora-app/example-decode$ 

Please what can I do in order to fix this? Even trying with import _"github.com/brocar/lorawan"_ the error reffering to _"undefined: PHYPayload"_ is still present. What does it means. please?
