### ISSUE TITLE
New datarates for Australia

### ISSUE THREAD

**Issue by couillardcharles** [brocaar/lorawan#30]
Hi @brocaar,
And thanks for your awesome projects!

I'm working on a LoRa deployment for Australia and just seen that the current config for au915_928 is not compatible with "LoRaWAN™ 1.0.2 Regional Parameters" specs.

When we try to connect a 1.0.2 device, we get the error "get join-accept txinfo error: lorawan/band: the given data-rate does not exist" during the join request.
That's because 1.0.2 introduces new datarates for Australia. 

I'm not sure the backwards compatibility are maintained between 1.0.0 and 1.0.2 so I don't know how to create a pull request for your project.
To start, i'll work on my own fork, but it could be good to integrate new datarates here.

Do you have any idea?

Thanks!

**Comment by brocaar** [comment]
You're correct! I did implement most of the 1.0.2 changes, but did not add the new data-rates for the AU band. Would you be able to create a pull request to add the missing data-rates (and the max-payload size values for these data-rates)?

I think this will impact <1.0.2 nodes in the sense that when the ADR engine will ask the node to change to DR4 or DR5, this will be rejected by the node. However, I think I could take the same approach as with https://github.com/brocaar/loraserver/issues/205. E.g. when a node nACKs a data-rate change, do not try to that data-rate again.
