### ISSUE TITLE
rxInfoSet --> phyPayload --> frmPayload Decrypted

### ISSUE THREAD

**Issue by RogerioCassares** [brocaar/lorawan#32]
Hi @brocaar , 

I am trying to get some information about decoding the framepayload at "frames_logs", at LoRa Server. 

I can get easily decode the payload at mqtt broker using a python script and then doing decode 64 to hex. So my payload sent over the node is the same hex value!

 But at postgresql database, the frame payload is some kind different. :/ 

When I receive from broker on my python application it appears "AQDwBQHy/1H/Wg==" (base64) --> x0100F00501F2FF51FF5A. Thats correct! It is the same frame I've sent over the node. 

However when i check on postgres' database, the frame header value also in base 64 would be the same, but there appears "+OU1NBf6d+EHcg==" --> xf8e5353417fa77e10772, 

Converting to hex I can take the data correctly size of information, but the frame payload doesnt.

Please give me a light how to proceed :) I will keep studynd and searching how to. In case i got it I will put here the answer. 

Best Regards,
Rogério Cassares Pires.

**Comment by RogerioCassares** [comment]
Hello @brocaar I am reading some opics and this topic is abbout LoRa-app-Server. Sorry for the mistake. I've read at LORa-app-Server doccumantations that: "Uplink data is published to a MQTT broker so that it is easy to subscribe to received data. Received data will be decrypted by LoRa App Server before being published" on <https://docs.loraserver.io/lora-app-server/overview/features/>

I am trying to use this decrypt file to decrypt the data from the database to my application. 

If I found before you read this i put the answer, Maybe they are crypto by AppSkey yet?

Thanks so much.
Best Regards
Rogério Cassares Pires

**Comment by RogerioCassares** [comment]
Thanks bro, I will test right now!

**Comment by RogerioCassares** [comment]
Hello @brocaar I got run the example above with correct NwkSkey and AppSkey. and the result of the debugging is showned bellow: 

go run example-decode/example-decode.go 
{"mhdr":{"mType":"ConfirmedDataUp","major":"LoRaWANR1"},"macPayload":{"fhdr":{"devAddr":"020155b2","fCtrl":{"adr":false,"adrAckReq":false,"ack":false,"fPending":false},"fCnt":2567,"fOpts":null},"fPort":100,"frmPayload":[{"bytes":"/eNicI0qbtGnVg=="}]},"mic":"04c2a38b"}
[1 0 253 5 1 242 255 86 255 93]

But at broker the result is: 

application/5/node/0004a30b001abe98/rx {"applicationID":"5","applicationName":"DET","nodeName":"DET-00","devEUI":"0004a30b001abe98","rxInfo":[{"mac":"7276ff00080801db","rssi":-105,"loRaSNR":9.5,"name":"7276ff00080801db","latitude":0,"longitude":0,"altitude":0}],"txInfo":{"frequency":902500000,"dataRate":{"modulation":"LORA","bandwidth":125,"spreadFactor":8},"adr":false,"codeRate":"4/5"},"fCnt":2567,"fPort":100,"data":"AQD9BQHy/1b/XQ=="}

Now i realize that "[1 0 253 5 1 242 255 86 255 93]" at decimal base reffers to "AQD9BQHy/1b/XQ=="at base64

Thank you so much for the lights!
Jesus bless you ! 
Best Regards
Rogério Cassares Pires

**Comment by brocaar** [comment]
Great!
