### ISSUE TITLE
Range problem

### ISSUE THREAD

**Issue by rohitkumar5293** [brocaar/lorawan#33]
Hi i have ported complete semtech Lorawan Stack to my MCU and using sx1276 via spi. I am able to send packet but my rssi value is -65 when i placed my end node close to gateway. whereas when i used Risinghf Modem with gateway at same distance his rssi value is -20 to -25. I am unable to debug error.

**Comment by brocaar** [comment]
I don't see how this is related to this lorawan package. A better place to ask for help might be https://forum.loraserver.io, but it looks like your issue is more hardware related.
