### ISSUE TITLE
Downlink Problem in "C" type device

### ISSUE THREAD

**Issue by kammyy** [brocaar/lorawan#34]
Hi,

I am sending Confirmed downlink to a C type device.
I have observed the following:
"The downlink is not sent immediately to the device. The downlink is sent after the next uplink message. And if the device does not send ACK back to the server then the server keeps on sending the downlink after each subsequent uplink. It never stops." 

Please help.

**Comment by brocaar** [comment]
Did you configure the device as Class-C in LoRa App Server and re-activated the device afterwards?

**Comment by kammyy** [comment]
Yes i did that.

I am using ABP method. Has it got something to do with it ?
I am using "relax frame counter" , can this be causing problem ?

The downlink is continuously sent by the server after each uplink. Even if a switch off the device and then switch it on again.  

Pls help

**Comment by kammyy** [comment]
The server does not stop sending downlink till i deleted the node in the server. How to stop the downlink ?

Thanks

**Comment by brocaar** [comment]
Either not use the `confirmed: true` or clear the queue yourself through the API (see the `/api` endpoint).

**Comment by kammyy** [comment]
Okay. Will do that. Thnx
