### ISSUE TITLE
OptNeg bit

### ISSUE THREAD

**Issue by Ssergeyy** [brocaar/lorawan#36]
Hello, Brocaar.
The OptNeg bit is described in the lorawan 1.1 specification. It is part of DLSetting JOIN ACCEPT. It characterizes the version of lorawan that is being used device. Now, your server not used it . Do you have plans to use it?

**Comment by brocaar** [comment]
LoRaWAN 1.1 is not supported currently but will be supported in the future. See also: https://github.com/brocaar/loraserver/issues/303.

**Comment by brocaar** [comment]
This will be added together with LoRaWAN 1.1 support.
