### ISSUE TITLE
Running example  function of the package 

### ISSUE THREAD

**Issue by alfonzodi** [brocaar/lorawan#49]
Hi,

 I'm trying to run the  `func ExamplePHYPayload_lorawan10Decode()` from **phypayload_test.go**. 
The result i had is : 
`=== RUN   ExamplePHYPayload_lorawan10Decode
--- PASS: ExamplePHYPayload_lorawan10Decode (0.01s)
PASS
Process finished with exit code 0`

But the output should be more detailed like : 
`// Output:
	// {"mhdr":{"mType":"ConfirmedDataUp","major":"LoRaWANR1"},"macPayload":{"fhdr":{"devAddr":"01020304","fCtrl":{"adr":false,"adrAckReq":false,"ack":false,"fPending":false,"classB":false},"fCnt":0,"fOpts":[{"cid":"DevStatusReq","payload":{"battery":115,"margin":7}}]},"fPort":10,"frmPayload":[{"bytes":"4mTU9w=="}]},"mic":"e117d2c0"}
	// [1 2 3 4]`

There is a specific option i should add in the go test, to show all the information ? 

M.A

**Comment by brocaar** [comment]
> But the output should be more detailed like

Why should it? The Go test passes as what the function prints equals the expected output as defined under `// Output:` this "magic" is handled by the Go test runner. See https://golang.org/pkg/testing/#hdr-Examples.
