### ISSUE TITLE
packets LOrawan

### ISSUE THREAD

**Issue by OniremE** [brocaar/lorawan#50]
I want to analyze the lorawan packages ... any way to do it?

**Comment by sophiekovalevsky** [comment]
@OniremE 

Probably a different approach to tackle this would be asking in the [community.](https://forum.chirpstack.io/) There are a lot people that may help you with it. In addition, I would recommend to describe what you are trying to do in a granular fashion so you can receive accurate feedback.

**Comment by brocaar** [comment]
I'm closing this issue as this is more a question for support. As @sophiekovalevsky recommends, please ask the community: https://forum.chirpstack.io. But also take a look at the library documentation and examples: https://pkg.go.dev/github.com/brocaar/lorawan?tab=doc#pkg-examples.
