### ISSUE TITLE
Which JS function derive AppKey ?

### ISSUE THREAD

**Issue by alfonzodi** [brocaar/lorawan#51]
Hi,

I am in LORAWAN 1.0.2, and I am looking for the function that generates the NwkSKey and the AppSkey fromroot key (appKey). 
I know it's two keys are generated in the generation of the join accept.
Are the two keys generated here? 
 **"lorawan / backend / join_request.go/" ====> func createJoinAnsPayload(ctx *context) error** 

<img width="813" alt="lrw_key" src="https://user-images.githubusercontent.com/57092573/76875734-3ea7d100-6871-11ea-89e6-bd82104add47.png">

**Comment by brocaar** [comment]
Please see https://github.com/brocaar/lorawan/blob/master/backend/joinserver/session_keys.go.
