### ISSUE TITLE
AS923 default frequency as refer to RP2-1.0.1 LoRaWAN® 

### ISSUE THREAD

**Issue by baried** [brocaar/lorawan#52]
Hi,
refer to RP2-1.0.1 LoRaWAN® Regional Parameters wich saying that AS923-1 represents the original AS923 plan; AS923-2 shifts the plan down 1.8MHz and AS923-3 shifts the plan down 6.6MHz, is there any update or how can i change the AS923 original default frequency to meet AS923-2 frequency plan??

**Comment by beegee-tokyo** [comment]
Any update on this? I am living in the Philippines, and Helium will start here soon. They will choose AS923-3 as Region. 
Support of AS923-2 and AS923-3 is getting important.

**Comment by brocaar** [comment]
@baried and @beegee-tokyo this has been implemented by the above commit. This will be included in the next ChirpStack Network Server release.
