### ISSUE TITLE
McKeyEncrypted byte order in McGroupSetupReq cmd

### ISSUE THREAD

**Issue by gyh1621** [brocaar/lorawan#53]
In LoRaWan spec 1.1 and LoRaWAN Remote Multicast spec 1.0.0, the "Conventions" sections all mentions that fields with multiple bytes are transferred in little endian:
> The octet order over the air for all multi-octet fields is little endian

But [in the implementation](https://github.com/brocaar/lorawan/blob/master/applayer/multicastsetup/multicastsetup.go#L393-L394), the "McKeyEncrypted" field which is 16 bytes long is just copied in its original order. Why is it not encoded in little endian form?

**Comment by brocaar** [comment]
I can't remember the reason behind this comment, but this works with existing FUOTA implementations. One reason I could think of is because the payload is encrypted. I fixed this in: https://github.com/brocaar/lorawan/commit/531a8de585bff4a339611577ce980019a51354a5.
