### ISSUE TITLE
CID.MarshalText() allways returns commands with Req  suffixes (the first MAC-command name for CID)

### ISSUE THREAD

**Issue by fancar** [brocaar/lorawan#56]
Hello Brocaar.
When I marshal PHYPayload struct with MacCommands in it, I always have the same name for MACcommand in both directions.

 ( (on pictures the  same behavior we can see via redis pubsub in chirpstack)
![Снимок экрана от 2021-04-28 15-04-58](https://user-images.githubusercontent.com/33594115/116403446-3d97f000-a836-11eb-8b7d-a0014d82807e.png)
![Снимок экрана от 2021-04-28 15-05-06](https://user-images.githubusercontent.com/33594115/116403458-3ffa4a00-a836-11eb-952f-18666f46a0af.png)

I see that there is a String() method generated for CID so it has no idea about the direction and there is no simple solution. 
Any plans or ideas on how to improve this?

**Comment by dsincl002c** [comment]
Hi @brocaar, any update on this? We are facing the same issue

**Comment by brocaar** [comment]
This is a cosmetic issue, not a real one. The "problem" is that both LinkCheckReq as LinkCheckAns CID have effectively the same value. Please refer to the LoRaWAN specs for a list of CIDs and you will see that all ...Req / ...Ans share the same byte value.

**Comment by dsincl002c** [comment]
I realize it is not a "real" issue, but it makes the string representation useless because it is deceiving. Seems better to have no `String()` method at all as opposed to returning the wrong thing.

**Comment by brocaar** [comment]
ChirpStack v4 contains a refactored lorawan library which does not have this issue :)
