### ISSUE TITLE
RTC settings

### ISSUE THREAD

**Issue by JindrichHavel** [brocaar/lorawan#58]
Is there any reliable way to change the RTC?
When I set the RTC date and time (HAL_RTC_SetTime / HAL_RTC_SetDate), the currently running timers (TimerEvent_t) may be broken!
We may need to stop all timers first, then change/set the date and time, and then restart the timers. But it's not quite easy ... How to do it easily?

**EDITED: Sorry you are right I got the wrong repository!**

**Comment by brocaar** [comment]
Did you post the question in the correct repository? This library is for constructing LoRaWAN PHYPayload frames and encoding these to an array of bytes. It has nothing to do with the HAL.

**Comment by JindrichHavel** [comment]
Incorrect entry
