### ISSUE TITLE
How to use loranWan documents？

### ISSUE THREAD

**Issue by xdj89** [brocaar/lorawan#66]
I didn't find an example of how to use it in the package

**Comment by brocaar** [comment]
Please see: https://pkg.go.dev/github.com/brocaar/lorawan#pkg-examples.

**Comment by xdj89** [comment]
Hello, first of all, thank the author for his reply. I haven't found any examples of how to send instructions to devices in this example. For example, to communicate with the serial port, there should be an example of opening the serial port and sending data to the serial port and interface serial port data

**Comment by 79-artisan** [comment]
> Please see: https://pkg.go.dev/github.com/brocaar/lorawan#pkg-examples.

Hello, first of all, thank the author for his reply. I haven't found any examples of how to send instructions to devices in this example. For example, to communicate with the serial port, there should be an example of opening the serial port and sending data to the serial port and interface serial port data

**Comment by 79-artisan** [comment]
@brocaar

**Comment by brocaar** [comment]
This library is not to interact with devices, it is to encode and decode LoRaWAN payloads.

**Comment by 79-artisan** [comment]
> This library is not to interact with devices, it is to encode and decode LoRaWAN payloads.

Thank you for your reply

@brocaar 
Do you know which libraries interact with devices

thank you

**Comment by sagar-patel-sls** [comment]
@79-artisan 

The library below interacts with devices.
[https://github.com/Lora-net/LoRaMac-node](https://github.com/Lora-net/LoRaMac-node)

The LoRaWAN stack API documentation can be found at:
[http://stackforce.github.io/LoRaMac-doc/](http://stackforce.github.io/LoRaMac-doc/)

Thank You

**Comment by 79-artisan** [comment]
> 
Hi @sagar-patel-sls 
Thank you for your reply. Is there a warehouse for Golang language and device interaction
Thank You
