### ISSUE TITLE
stm32wl55

### ISSUE THREAD

**Issue by tcpipchip** [brocaar/lorawan#67]
Dear Sir

I work to a representative of Wisol in South America.

I am starting blogs about TINYGO and our module is the LSM110A (STM32WL55)

https://ninab3-python.blogspot.com/2022/12/u-blox-nina-b302-rodando-tinygo.html
https://ninab3-python.blogspot.com/2022/12/wisol-lsm110a-rodando-tinygo-blynk-led.html
Both are running...

Can you help me where to include the LoRaWAN package to compile it on TINYGO FOLDER structure ?

├───bin
├───lib
│   ├───clang
│   │   └───include
│   ├───CMSIS
│   │   └───CMSIS
│   │       └───Include
│   ├───compiler-rt-builtins
│   │   ├───aarch64
│   │   ├───arm
│   │   ├───Darwin-excludes
│   │   ├───hexagon
│   │   ├───i386
│   │   ├───macho_embedded
│   │   ├───ppc
│   │   ├───riscv
│   │   ├───ve
│   │   └───x86_64
│   ├───macos-minimal-sdk
│   │   ├───download
│   │   ├───src
│   │   │   ├───arm64
│   │   │   ├───usr
│   │   │   │   └───include
│   │   │   │       ├───arm
│   │   │   │       ├───arpa
│   │   │   │       ├───i386
│   │   │   │       ├───libkern
│   │   │   │       │   ├───arm
│   │   │   │       │   └───i386
│   │   │   │       ├───mach
│   │   │   │       │   ├───arm
│   │   │   │       │   ├───i386
│   │   │   │       │   └───machine
│   │   │   │       ├───machine
│   │   │   │       ├───malloc
│   │   │   │       ├───protocols
│   │   │   │       ├───secure
│   │   │   │       ├───sys
│   │   │   │       │   ├───_pthread
│   │   │   │       │   └───_types
│   │   │   │       ├───xlocale
│   │   │   │       └───_types
│   │   │   └───x86_64
│   │   └───test
│   ├───mingw-w64
│   │   ├───mingw-w64-crt
│   │   │   ├───def-include
│   │   │   └───lib-common
│   │   └───mingw-w64-headers
│   │       ├───crt
│   │       │   ├───sdks
│   │       │   ├───sec_api
│   │       │   │   └───sys
│   │       │   └───sys
│   │       └───defaults
│   │           └───include
│   │               └───sdks
│   ├───musl
│   │   ├───arch
│   │   │   ├───aarch64
│   │   │   │   └───bits
│   │   │   ├───arm
│   │   │   │   └───bits
│   │   │   ├───generic
│   │   │   │   └───bits
│   │   │   ├───i386
│   │   │   │   └───bits
│   │   │   └───x86_64
│   │   │       └───bits
│   │   ├───crt
│   │   ├───include
│   │   │   ├───arpa
│   │   │   ├───net
│   │   │   ├───netinet
│   │   │   ├───netpacket
│   │   │   ├───scsi
│   │   │   └───sys
│   │   └───src
│   │       ├───env
│   │       ├───errno
│   │       ├───exit
│   │       │   └───arm
│   │       ├───include
│   │       │   ├───arpa
│   │       │   └───sys
│   │       ├───internal
│   │       │   ├───i386
│   │       │   └───sh
│   │       ├───malloc
│   │       ├───math
│   │       │   ├───aarch64
│   │       │   ├───arm
│   │       │   ├───i386
│   │       │   ├───mips
│   │       │   ├───powerpc
│   │       │   ├───powerpc64
│   │       │   ├───riscv64
│   │       │   ├───s390x
│   │       │   ├───x32
│   │       │   └───x86_64
│   │       ├───mman
│   │       ├───signal
│   │       │   ├───aarch64
│   │       │   ├───arm
│   │       │   ├───i386
│   │       │   ├───m68k
│   │       │   ├───microblaze
│   │       │   ├───mips
│   │       │   ├───mips64
│   │       │   ├───mipsn32
│   │       │   ├───or1k
│   │       │   ├───powerpc
│   │       │   ├───powerpc64
│   │       │   ├───riscv64
│   │       │   ├───s390x
│   │       │   ├───sh
│   │       │   ├───x32
│   │       │   └───x86_64
│   │       ├───stdio
│   │       ├───string
│   │       │   ├───arm
│   │       │   ├───i386
│   │       │   └───x86_64
│   │       ├───thread
│   │       │   ├───aarch64
│   │       │   ├───arm
│   │       │   ├───i386
│   │       │   ├───m68k
│   │       │   ├───microblaze
│   │       │   ├───mips
│   │       │   ├───mips64
│   │       │   ├───mipsn32
│   │       │   ├───or1k
│   │       │   ├───powerpc
│   │       │   ├───powerpc64
│   │       │   ├───riscv64
│   │       │   ├───s390x
│   │       │   ├───sh
│   │       │   ├───x32
│   │       │   └───x86_64
│   │       ├───time
│   │       └───unistd
│   │           ├───mips
│   │           ├───mips64
│   │           ├───mipsn32
│   │           ├───sh
│   │           └───x32
│   ├───nrfx
│   │   ├───doc
│   │   │   ├───buildfiles
│   │   │   └───config_dox
│   │   ├───drivers
│   │   │   ├───include
│   │   │   └───src
│   │   │       └───prs
│   │   ├───hal
│   │   ├───helpers
│   │   ├───mdk
│   │   ├───soc
│   │   └───templates
│   ├───picolibc
│   │   └───newlib
│   │       ├───libc
│   │       │   ├───ctype
│   │       │   ├───include
│   │       │   │   ├───machine
│   │       │   │   ├───rpc
│   │       │   │   ├───ssp
│   │       │   │   └───sys
│   │       │   ├───locale
│   │       │   ├───string
│   │       │   └───tinystdio
│   │       │       └───ryu
│   │       └───libm
│   │           ├───common
│   │           └───math
│   └───wasi-libc
│       └───sysroot
│           ├───include
│           │   ├───arpa
│           │   ├───bits
│           │   ├───net
│           │   ├───netinet
│           │   ├───netpacket
│           │   ├───scsi
│           │   ├───sys
│           │   └───wasi
│           └───lib
│               └───wasm32-wasi
├───pkg
│   ├───thumbv6m-unknown-unknown-eabi-cortex-m0
│   │   ├───compiler-rt
│   │   └───picolibc
│   │       └───include
│   ├───thumbv6m-unknown-unknown-eabi-cortex-m0plus
│   │   ├───compiler-rt
│   │   └───picolibc
│   │       └───include
│   └───thumbv7em-unknown-unknown-eabi-cortex-m4
│       ├───compiler-rt
│       └───picolibc
│           └───include
├───src
│   ├───crypto
│   │   ├───internal
│   │   │   └───boring
│   │   │       └───sig
│   │   └───rand
│   ├───device
│   │   ├───arm
│   │   ├───arm64
│   │   ├───avr
│   │   ├───esp
│   │   ├───kendryte
│   │   ├───nrf
│   │   ├───nxp
│   │   ├───riscv
│   │   ├───rp
│   │   ├───sam
│   │   ├───sifive
│   │   └───stm32
│   ├───examples
│   │   ├───adc
│   │   ├───blinkm
│   │   ├───blinky1
│   │   ├───blinky2
│   │   ├───button
│   │   ├───button2
│   │   ├───can
│   │   ├───caninterrupt
│   │   ├───dac
│   │   ├───echo
│   │   ├───echo2
│   │   ├───gba-display
│   │   ├───hid-keyboard
│   │   ├───hid-mouse
│   │   ├───i2s
│   │   ├───mcp3008
│   │   ├───memstats
│   │   ├───microbit-blink
│   │   ├───pininterrupt
│   │   ├───pwm
│   │   ├───rand
│   │   ├───serial
│   │   ├───systick
│   │   ├───temp
│   │   ├───test
│   │   ├───uart
│   │   ├───usb-midi
│   │   └───wasm
│   │       ├───callback
│   │       ├───export
│   │       ├───invoke
│   │       ├───main
│   │       └───slices
│   ├───internal
│   │   ├───bytealg
│   │   ├───fuzz
│   │   ├───reflectlite
│   │   └───task
│   ├───machine
│   │   └───usb
│   │       ├───cdc
│   │       ├───hid
│   │       │   ├───keyboard
│   │       │   └───mouse
│   │       └───midi
│   ├───net
│   ├───os
│   │   └───exec
│   ├───reflect
│   ├───runtime
│   │   ├───cgo
│   │   ├───debug
│   │   ├───internal
│   │   │   └───sys
│   │   ├───interrupt
│   │   ├───pprof
│   │   ├───trace
│   │   └───volatile
│   ├───sync
│   ├───syscall
│   └───testing
└───targets

Thanks!

**Comment by brocaar** [comment]
Sorry, I don't know. I don't have experience with TinyGo. Please note that this repository provides the encoding / decoding, it doesn't provide a full LoRaWAN stack.
