### ISSUE TITLE
Issue with LoRaWAN 1.1.0 joining with Network server

### ISSUE THREAD

**Issue by Sravs007** [brocaar/lorawan#72]
Hi,

We are using SX1262 LoRa module with LoRaWAN 1.0.3 to connect with Network Server and this is working fine. When we try to connect using LoRaWAN 1.1.0, we are getting join request and join accept also at ChipStack but at end device side its showing LORAMAC_HANDLER_ERROR. Are we missing something. Please let me know. Thanks.

**Comment by brocaar** [comment]
Please note that this repo does not contain the source-code that returns the `LORAMAC_HANDLER_ERROR`. You probably want to take a look at: https://github.com/lora-net/loramac-node.
