### ISSUE TITLE
LoRaWAN1.1 and LoRaWAN 1.0.4 

### ISSUE THREAD

**Issue by Sravs007** [brocaar/lorawan#73]
Hi Brocaar,

We are currently using the LoRaMAC_node stack for LoRaWAN v1.0.3 in our project and are planning to upgrade it. Our target is to move to LoRaWAN 1.1, but we also consider using LoRaWAN v1.0.4. Is there a release of the LoRaBasicsModem from Semtech that supports LoRaWAN 1.1? Additionally, if we opt for LoRaBasicsModem with LoRaWAN v1.0.4, could you highlight the key differences or potential feature limitations compared to LoRaWAN 1.1? Understanding these differences is crucial for us to make a decision.

Thank you,
Sravs

**Comment by brocaar** [comment]
This is not the right place to ask such questions. GitHub issues are for bugs or new features. You could post your question at the community forum: https://forum.chirpstack.io/.
