### ISSUE TITLE
MHDR

### ISSUE THREAD

**Issue by mihailstefanov** [brocaar/lorawan#9]
I have a question(not so a issue), by the documentation MHDR has one more field RFU. Why you skipped in your implementation, is there some reason?

**Comment by brocaar** [comment]
``RFU`` means reserved for future use :wink: So currently it is unspecified what these two bits represent. They might get a purpose in future lorawan versions (e.g. when they need more space for the ``Major`` field), but currently they can't be used. Hope this answers your question.
